# Uncomment the next line to define a global platform for your project
 platform :ios, '15.0'

target 'test_ottu' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'ottu_checkout_sdk', :git => 'https://github.com/ottuco/ottu-ios.git'
end
